version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/" # Location of Docker manifests
    schedule:
      interval: "weekly"
