version: "3.2"
services:
  frontend:
    build:
      context: ./frontend
    environment:
      - WATCHPACK_POLLING="true"
    volumes:
      - /app/node_modules
      - ./src:/app/src
    ports:
      - "8080:3000"
  api:
    depends_on:
      - postgres
    build:
      context: ./api
    environment:
      - WATCHPACK_POLLING="true"
    volumes:
      - /app/node_modules
      - ./src:/app/src
    ports:
      - "3000:8000"
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
