version: "3.2"
services:
  api:
    depends_on:
      - postgres
    build:
      context: ./
    environment:
      - WATCHPACK_POLLING="true"
    volumes:
      - /app/node_modules
      - ./src:/app/src
    ports:
      - "3000:8000"
