name: Deploy to Github Pages on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          GIT_REPO: github.com/derekmborges/pairminator.git
          GIT_NAME: derekmborges
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
             echo "Deploying to Github Pages"
             git config --global user.email ${{ secrets.GIT_EMAIL }}
             git config --global user.name $GIT_NAME
             git remote set-url origin https://$GIT_NAME:${{ secrets.ACTIONS_BOT_TOKEN }}@$GIT_REPO
             yarn
             yarn deploy
